name: compile-all-scores
run-name: Compiling lilypond scores for Cyprus Choir Club
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: codello/setup-lilypond@main
        with:
          lilypond-version: 2.24
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jinja2
      - run: lilypond *.ly
      - run: python3 pages/generate-static.py
      - uses: actions/upload-artifact@v4
        with:
          name: pdf-scores
          path: |
            *.pdf
            *.midi
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: out/pages

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
